[package]
name = "transfer_eth"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.2.1", features = ["full"] }
dotenv = "0.15.0"
tokio = { version = "1.49.0", features = ["full"] }

